name: simple_network_handler
description: A package for handling network errors with error registry and interceptors
version: 1.0.0
repository: https://github.com/keep-it-simple-dev/simple_network_handler
issue_tracker: https://github.com/keep-it-simple-dev/simple_network_handler/issues
topics: [dio, network, error-handling]

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  dartz: ^0.10.1
  dio: ^5.8.0+1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0